// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUiI7doV59B1hFkruHYR5iM4toAmx_a-s',
    appId: '1:756282794403:web:de62f502380d4e2146ba16',
    messagingSenderId: '756282794403',
    projectId: 'mad-cw08',
    authDomain: 'mad-cw08.firebaseapp.com',
    storageBucket: 'mad-cw08.firebasestorage.app',
    measurementId: 'G-EHFCJSH1J6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtIZE7NEtibCTTVIfncS-Jz08VllpClxc',
    appId: '1:756282794403:android:750b2e13d24e6c6346ba16',
    messagingSenderId: '756282794403',
    projectId: 'mad-cw08',
    storageBucket: 'mad-cw08.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrMVUedR0Kk84EIpZ3hQ63TWez4-NORu4',
    appId: '1:756282794403:ios:e6aefda4f7b33aca46ba16',
    messagingSenderId: '756282794403',
    projectId: 'mad-cw08',
    storageBucket: 'mad-cw08.firebasestorage.app',
    iosBundleId: 'com.example.madCw08',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrMVUedR0Kk84EIpZ3hQ63TWez4-NORu4',
    appId: '1:756282794403:ios:e6aefda4f7b33aca46ba16',
    messagingSenderId: '756282794403',
    projectId: 'mad-cw08',
    storageBucket: 'mad-cw08.firebasestorage.app',
    iosBundleId: 'com.example.madCw08',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUiI7doV59B1hFkruHYR5iM4toAmx_a-s',
    appId: '1:756282794403:web:fa9164462a9592fa46ba16',
    messagingSenderId: '756282794403',
    projectId: 'mad-cw08',
    authDomain: 'mad-cw08.firebaseapp.com',
    storageBucket: 'mad-cw08.firebasestorage.app',
    measurementId: 'G-0YQTBJPNG1',
  );
}
